### ISSUE TITLE
Fix main page get spam.

### ISSUE THREAD

**Issue by JackDunlop** [JackDunlop/SquashAustraliaCapstone#23]
![image](https://github.com/user-attachments/assets/2b69487d-0aef-4be8-bd6f-0e0879813df4)

**Comment by Aledhole** [comment]
![Capture](https://github.com/user-attachments/assets/97ca7ce1-3ba6-4c83-92ae-197e652cff9a)

**Comment by Aledhole** [comment]
fixed
